config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  root to: "offerings#dashboard"

  resources :courses

  # Offerings
  get "/classes/", to: "offerings#index", as: "offerings"
  get "/classes/new", to: "offerings#new", as: "new_offering"
  get "/classes/dashboard", to: "offerings#dashboard", as: "user_dashboard"
  get "/classes/:id", to: "offerings#show", as: "offering"
  get "/classes/:id/sign_up", to: "offerings#sign_up", as: "sign_up_for_offering"
  get "/casses/:id/drop", to: "offerings#drop", as: "drop_offering"
  post "/classes/", to: "offerings#create"
  delete "/classes/:id", to: "offerings#destroy"
end

app/models/class_signup.rb
class ClassSignup < ActiveRecord::Base
  belongs_to :offering
  belongs_to :user
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :section, :number, :name, :length

  def to_s
    "#{section}#{number} #{name}"
  end

  # DEBUGGING ONLY
  def self._create_random
    c = Course.new
    c.section = %w(GEN EDU TOM ACK ZZZ).sample
    c.number = Random.rand(100) * 10
    c.name = 3.times.map { %w(test random tom class word mastery debug development).sample }.join ' '
    c.length = %w(30 60 90 120).sample
    c.save
  end
end

app/models/offering.rb
class Offering < ActiveRecord::Base
  belongs_to :user
  belongs_to :course
  has_many :class_signups
  has_many :students, source: :user, through: :class_signups

  validates_presence_of :size, :location, :course_id, :scheduled_at

  before_destroy { class_signups.destroy_all }

  scope :available, -> { where('scheduled_at > ?', Time.now).where('size > signed_up') }

  def available?
    empty_seats? && scheduled_at >= Time.now
  end

  def empty_seats?
    size > signed_up
  end

  # DEBUGGING ONLY
  def self._create_random
    o = Offering.new
    o.course = Course.all.sample
    o.size = Random.rand(20) + 10
    o.scheduled_at = Date.today + (rand(7)).days
    o.location = ['4th floor Cafe', '5th floor boardroom', 'Washington Station'].sample
    o.user = User.instructors.sample
    o.signed_up = 0
    o.save
  end
end

app/models/scheduled_course.rb
class ScheduledCourse < ActiveRecord::Base
  belongs_to :user
  belongs_to :course
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:google_oauth2]

  has_many :offerings
  has_many :class_signups
  has_many :student_offerings, source: :offering, through: :class_signups

  def to_s
    name
  end

  def signed_up_for
    student_offerings.where('offerings.scheduled_at > ?', Time.now)
  end

  def signed_up_for? offering
    ClassSignup.where(user_id: id, offering_id: offering.id).count > 0
  end

  def sign_up_for(offering)
    unless signed_up_for? offering
      ClassSignup.create(user_id: id, offering: offering)
      offering.update_attribute(:signed_up, offering.students.count)
    end
  end

  def drop_offering(offering)
    if signed_up_for? offering
      ClassSignup.find_by(user_id: id, offering: offering).destroy
      offering.update_attribute(:signed_up, offering.students.count)
    end
  end

  def is_admin?
    admin_flag
  end

  def is_instructor?
    instructor_flag
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.name = auth.info.name
      user.password = Devise.friendly_token[0,20]
    end
  end

  def self.instructors
    where(instructor_flag: true)
  end
end

app/models/waiting_list.rb
class WaitingList < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  def index
    @courses = Course.all
  end

  # GET /courses/1
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  def create
    @course = Course.new(course_params)

    if @course.save
      redirect_to @course, notice: 'Course was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /courses/1
  def update
    if @course.update(course_params)
      redirect_to @course, notice: 'Course was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /courses/1
  def destroy
    @course.destroy
    redirect_to courses_url, notice: 'Course was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def course_params
      params.require(:course).permit(:section, :number, :name, :description, :length, :user_id)
    end
end

app/controllers/offerings_controller.rb
class OfferingsController < ApplicationController

  before_filter :set_offering, only: [:show, :sign_up, :drop, :destroy]

  def index
    @offerings = Offering.where("scheduled_at >= ?", Time.now).order(:scheduled_at).paginate(page: params[:page], per_page: 10)
  end

  def new
    @offering = Offering.new
  end

  def show
  end

  def sign_up
    @offering = Offering.find params[:id]

    if @offering.signed_up == @offering.size
      redirect_to :back, alert: "Sorry, but that class appears to be full."
      return
    end

    if current_user.signed_up_for? @offering
      redirect_to :back, alert: "You're already signed up for that course."
      return
    end

    if current_user.sign_up_for(@offering)
      redirect_to :back, notice: "You have successfully signed up for this class."
    else
      redirect_to :back, alert: "There was an error signing up for that class. Please try again."
    end
  end

  def drop
    if current_user.signed_up_for? @offering
      current_user.drop_offering @offering
      redirect_to :back, notice: "You have successfully dropped this class."
    else
      redirect_to :back, alert: "You were not signed up for that class."
    end
  end

  def create
    @offering = Offering.new(scheduled_course_params)
    if @offering.save
      redirect_to @offering, notice: 'Scheduled course was successfully created.'
    else
      render :new
    end
  end

  # Main user dashboard
  def dashboard
    @offerings = {
        signed_up: current_user.signed_up_for,
        starting_soon: Offering.available.order(:scheduled_at).limit(5)
    }
  end

  # TODO Should only be able to destroy if admin probably
  def destroy
    if @offering.destroy
      redirect_to offerings_path, notice: "Class was successfully deleted."
    else
      redirect_to offerings_path, alert: "Could not delete class. Please try again."
    end
  end

  private
    def set_offering
      @offering = Offering.find params[:id]
    end

    def scheduled_course_params
      params.require(:offering).permit(:course_id, :size, :scheduled_at, :location)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/offerings_helper.rb
module OfferingsHelper
end

app/views/Offerings/new.html.erb
<h1>New Scheduled Course</h1>

<%= render 'form' %>

<%= link_to 'Back', scheduled_courses_path %>

app/views/Offerings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Course:</strong>
  <%= @offering.course %>
</p>

<p>
  <strong>Size:</strong>
  <%= @offering.size %>
</p>

<p>
  <strong>Scheduled on:</strong>
  <%= @offering.scheduled_on %>
</p>

<p>
  <strong>Location:</strong>
  <%= @offering.location %>
</p>

<p>
  <strong>User:</strong>
  <%= @offering.user %>
</p>

<%= link_to 'Edit', edit_scheduled_course_path(@offering) %> |
<%= link_to 'Back', scheduled_courses_path %>

app/views/application/_navbar.html.erb
<nav class="navbar">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="glyphicon glyphicon-th-list"></span>
      </button>
      <a class="navbar-brand" href="/">Mastery</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Dashboard</a></li>
        <li><a href="/classes/">All Classes</a></li>
        <li><a href="/users/portfolio">My Portfolio</a></li>
        <% if current_user.is_instructor? %>
          <li><a href="/instructors/dashboard">Instructor Dashboard</a></li>
        <% end %>
        <% if current_user.is_admin? %>
          <li><a href="/courses/">Courses</a></li>
          <li><a href="/admin/dashboard">Admin Dashboard</a></li>
        <% end %>
      </ul>
      <div class="navbar-text pull-right">
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= "(admin)" if current_user.is_admin? %>
          <%= "(instructor)" if current_user.is_instructor? %>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% end %>
      </div>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/courses/_course.html.erb
<tr>
  <td><%= "#{course.section}#{course.number}" %></td>
  <td><%= course.name %></td>
  <td><%= course.length %> minutes</td>
  <td><%= course.user %></td>
  <td>
    <%= link_to 'View', course %>
    <%= link_to 'Edit', edit_course_path(course) %>
    <%= link_to 'Delete', course_path(course), method: :delete, data: {confirm: "Are you sure you want to delete this course?"} %>
  </td>
</tr>

app/views/courses/_form.html.erb
<%= simple_form_for(@course) do |f| %>
  <%= f.input :section %>
  <%= f.input :number %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :length, label: "Length in minutes" %>
  <%= f.label "Teacher" %>
  <%= f.collection_select(:user_id, User.instructors, :id, :name, {include_blank: "None"}, {class: "form-control"}) %><br />
  <%= f.button :submit, class: "btn btn-success" %>
  <%= link_to "Cancel", courses_path, class: "btn btn-danger" %>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form' %>

app/views/courses/index.html.erb
<h1>All Courses</h1>
<table class="table">
  <thead>
    <tr>
      <th>Number</th>
      <th>Name</th>
      <th>Length</th>
      <th>Instructor</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= render @courses %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path, class: "btn btn-success" %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form' %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Section:</strong>
  <%= @course.section %>
</p>

<p>
  <strong>Number:</strong>
  <%= @course.number %>
</p>

<p>
  <strong>Name:</strong>
  <%= @course.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @course.description %>
</p>

<p>
  <strong>Length:</strong>
  <%= @course.length %>
</p>

<p>
  <strong>User:</strong>
  <%= @course.user %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mastery</title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Mastery</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Dashboard</a></li>
        <li><a href="/offerings/">All Offerings</a></li>
        <li><a href="/users/portfolio">My Portfolio</a></li>
      </ul>
      <div class="navbar-text pull-right">
        <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
      </div>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<div class="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>
</div>
<%= javascript_include_tag 'application' %>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mastery</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <br /><br />
  <% if notice %>
    <div class="alert alert-success"><%= notice %></div>
  <% end %>
  <% if alert %>
    <div class="alert alert-danger"><%= alert %></div>
  <% end %>
  <%= yield %>
</div>
<%= javascript_include_tag 'application' %>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</body>
</html>

app/views/offerings/_form.html.erb
<%= simple_form_for(@offering) do |f| %>
  <%= f.label "Course" %>
  <%= f.collection_select(:course_id, Course.all, :id, :to_s, {}, {class: "form-control"}) %><br />
  <%= f.input :size %>
  <%= f.input :scheduled_at, label: "Start Time", as: :date_time_picker %>
  <%= f.input :location %>
  <%= f.button :submit, class: "btn btn-success" %>
  <%= link_to "Cancel", offerings_path, class: "btn btn-danger" %>
<% end %>

app/views/offerings/_offering.html.erb
<tr>
  <td><%= offering.course %></td>
  <td><%= offering.scheduled_at.strftime('%h %d %l:%M %p') %></td>
  <td><%= offering.signed_up %>/<%= offering.size %></td>
  <td>0/0</td>
  <td class="text-right">
    <% if current_user.signed_up_for? offering %>
      <%= link_to "Drop class", drop_offering_path(offering), class: "btn btn-danger", data: {confirm: "Are you sure you want to drop this class?"} %>
    <% else %>
      <%= link_to "Sign up", sign_up_for_offering_path(offering), class: "btn btn-success" %>
    <% end %>
    <%= link_to "Details", offering, class: "btn btn-default" %>
    <% if current_user.is_admin? %>
      <%= link_to "Delete", offering_path(offering), method: :delete, data: {confirm: "Are you sure you want to delete this class?"}, class: "btn btn-danger" %>
    <% end %>
  </td>
</tr>

app/views/offerings/dashboard.html.erb
<h1>Listing Offerings</h1>
<h2>Signed Up</h2>
<table class="table">
  <thead>
  <tr>
    <th>Course</th>
    <th>Start Time</th>
    <th>Signed Up</th>
    <th>Wait List</th>
    <th></th>
  </tr>
  </thead>

  <tbody>
    <% @offerings[:signed_up].each do |o| %>
      <%= render partial: 'offering', object: o %>
    <% end %>
  </tbody>
</table>

<h2>Starting Soon</h2>
<table class="table">
  <thead>
  <tr>
    <th>Course</th>
    <th>Start Time</th>
    <th>Signed Up</th>
    <th>Wait List</th>
    <th></th>
  </tr>
  </thead>

  <tbody>
    <% @offerings[:starting_soon].each do |o| %>
      <%= render partial: 'offering', object: o %>
    <% end %>
  </tbody>
</table>

app/views/offerings/index.html.erb
<h1>Listing Offerings</h1>
<table class="table">
  <thead>
    <tr>
      <th>Course</th>
      <th>Start Time</th>
      <th>Signed Up</th>
      <th>Wait List</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <%= render @offerings %>
  </tbody>
</table>
<%= will_paginate @offerings, renderer: BootstrapPagination::Rails %>

<br>
<% if current_user.is_admin? %>
  <%= link_to "Schedule a class", new_offering_path, class: "btn btn-primary" %>
<% end %>

app/views/offerings/new.html.erb
<h1>Schedule a class</h1>
<%= render 'form' %>

app/views/offerings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Course:</strong>
  <%= @offering.course %>
</p>

<p>
  <strong>Size:</strong>
  <%= @offering.size %>
</p>

<p>
  <strong>Scheduled on:</strong>
  <%= @offering.scheduled_at %>
</p>

<p>
  <strong>Location:</strong>
  <%= @offering.location %>
</p>

<p>
  <strong>User:</strong>
  <%= @offering.user %>
</p>

<%= link_to 'Back', offerings_path %>

app/views/scheduled_courses/_form.html.erb
<%= form_for(@scheduled_course) do |f| %>
  <% if @scheduled_course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scheduled_course.errors.count, "error") %> prohibited this scheduled_course from being saved:</h2>

      <ul>
      <% @scheduled_course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :course %><br>
    <%= f.text_field :course %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :scheduled_on %><br>
    <%= f.text_field :scheduled_on %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scheduled_courses/edit.html.erb
<h1>Editing Scheduled Course</h1>

<%= render 'form' %>

<%= link_to 'Show', @scheduled_course %> |
<%= link_to 'Back', scheduled_courses_path %>

app/views/scheduled_courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Scheduled Courses</h1>

<table>
  <thead>
    <tr>
      <th>Course</th>
      <th>Size</th>
      <th>Scheduled on</th>
      <th>Location</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scheduled_courses.each do |scheduled_course| %>
      <tr>
        <td><%= scheduled_course.course %></td>
        <td><%= scheduled_course.size %></td>
        <td><%= scheduled_course.scheduled_on %></td>
        <td><%= scheduled_course.location %></td>
        <td><%= scheduled_course.user %></td>
        <td><%= link_to 'Show', scheduled_course %></td>
        <td><%= link_to 'Edit', edit_scheduled_course_path(scheduled_course) %></td>
        <td><%= link_to 'Destroy', scheduled_course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Scheduled course', new_scheduled_course_path %>

app/views/scheduled_courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Course:</strong>
  <%= @scheduled_course.course %>
</p>

<p>
  <strong>Size:</strong>
  <%= @scheduled_course.size %>
</p>

<p>
  <strong>Scheduled on:</strong>
  <%= @scheduled_course.scheduled_on %>
</p>

<p>
  <strong>Location:</strong>
  <%= @scheduled_course.location %>
</p>

<p>
  <strong>User:</strong>
  <%= @scheduled_course.user %>
</p>

<%= link_to 'Edit', edit_scheduled_course_path(@scheduled_course) %> |
<%= link_to 'Back', scheduled_courses_path %>